#region AutoGenerated
using UnityEngine;

namespace Sisus.Debugging
{
	/// <summary>
	/// Defines a channel for a message logged to the Console.
	/// <para>
	/// The contents of this class are auto-generated based on the channels added in Project Settings > Console.
	/// </para>
	/// <seealso cref="Debug.Log(int, string, Object)"/>
	/// </summary>
	public static class Channel
	{
		public const int None = 0;
#if UNITY_2019_2_OR_NEWER
		[UnityEngine.InspectorName("Sanjeev Prasad")]
#endif
		public const int Sanjeev_Prasad = 1;
		public const int Krystal = 2;
	}
}
#endregion